# Generated by Django 5.0.1 on 2024-03-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_suitegoodsrec_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specgoods',
            name='goods_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='货品编号'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='spec_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='商家编码'),
        ),
        migrations.AlterField(
            model_name='suitegoodsrec',
            name='goods_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='货品编号'),
        ),
    ]
