# Generated by Django 5.0.1 on 2024-04-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_specgoods_allow_below_cost_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformgoods',
            name='disable_syn_until',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='disabled_reason',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='flag_name',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='goods_id',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='goods_name',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='hold_stock_type',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='is_auto_delisting',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='is_auto_listing',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='is_auto_match',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='is_disable_syn',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='last_syn_num',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='last_syn_time',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='price',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='spec_id',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='spec_outer_id',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='status',
        ),
        migrations.RemoveField(
            model_name='platformgoods',
            name='syn_platform_allocation_ratio',
        ),
        migrations.RemoveField(
            model_name='suitegoodsrec',
            name='created',
        ),
        migrations.RemoveField(
            model_name='suitegoodsrec',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='suitegoodsrec',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='suitegoodsrec',
            name='spec_code',
        ),
        migrations.RemoveField(
            model_name='suitegoodsrec',
            name='stock_num',
        ),
        migrations.RemoveField(
            model_name='suitegoodsrec',
            name='suite_barcode',
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='goods_brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='货品品牌'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='goods_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='货品分类'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='img_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='图片链接'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='platform_goods_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台货品id'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='platform_goods_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='平台货品名称'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='platform_outer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台货品编号'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='platform_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='平台价格'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='platform_spec_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台规格ID'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='platform_spec_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台规格名称'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='platform_spec_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台商家编码'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='platform_spec_outer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台规格编码'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='platform_spec_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台类目'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='platform_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台状态'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='零售价'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='spec_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='规格码'),
        ),
        migrations.AddField(
            model_name='platformgoods',
            name='spec_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商家编码'),
        ),
        migrations.AddField(
            model_name='suitegoodsrec',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='suitegoodsrec',
            name='goods_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='suitegoodsrec',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='市场价'),
        ),
        migrations.AddField(
            model_name='suitegoodsrec',
            name='member_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='会员价'),
        ),
        migrations.AddField(
            model_name='suitegoodsrec',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='suitegoodsrec',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='零售价'),
        ),
        migrations.AddField(
            model_name='suitegoodsrec',
            name='suite_short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='组合装简称'),
        ),
        migrations.AddField(
            model_name='suitegoodsrec',
            name='ware_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='外部编码'),
        ),
        migrations.AddField(
            model_name='suitegoodsrec',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='重量(kg)'),
        ),
        migrations.AddField(
            model_name='suitegoodsrec',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='批发价'),
        ),
        migrations.AlterField(
            model_name='platformgoods',
            name='hold_stock',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='平台库存占用量'),
        ),
        migrations.AlterField(
            model_name='platformgoods',
            name='match_target_type',
            field=models.CharField(blank=True, help_text='0未指定，1单品，2组合装', max_length=100, null=True, verbose_name='是否组合装'),
        ),
        migrations.AlterField(
            model_name='platformgoods',
            name='outer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='货品编号'),
        ),
        migrations.AlterField(
            model_name='platformgoods',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='店铺名称'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='allow_below_cost_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='允许低于成本价'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='aux_unit_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='辅助单位'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主条码'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='goods_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='货品编号'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='goods_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='large_type',
            field=models.CharField(blank=True, help_text='大件类别 0、非大件;1、普通大;2、独立大件（不可和小件一起发）;3、按箱规拆分;-1、非单发件', max_length=100, null=True, verbose_name='大件类别（拆分）'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='简称'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='sn_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='启用序列号'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='spec_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='规格码'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='spec_modified',
            field=models.DateTimeField(blank=True, help_text='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='spec_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商家编码'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='tax_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='税务编码'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='u9_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='U9料号'),
        ),
        migrations.AlterField(
            model_name='specgoods',
            name='unit_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='基本单位'),
        ),
        migrations.AlterField(
            model_name='suitegoodsrec',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='条码'),
        ),
        migrations.AlterField(
            model_name='suitegoodsrec',
            name='goods_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='单品名称'),
        ),
        migrations.AlterField(
            model_name='suitegoodsrec',
            name='goods_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='单品货品编号'),
        ),
        migrations.AlterField(
            model_name='suitegoodsrec',
            name='is_fixed_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='是否固定价格'),
        ),
        migrations.AlterField(
            model_name='suitegoodsrec',
            name='spec_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='单品规格名称'),
        ),
        migrations.AlterField(
            model_name='suitegoodsrec',
            name='spec_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='单品商家编码'),
        ),
        migrations.AlterField(
            model_name='suitegoodsrec',
            name='suite_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组合装商家编码'),
        ),
    ]
