# Generated by Django 5.0.1 on 2024-04-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_platformgoods_goods_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='品牌')),
                ('spu', models.CharField(blank=True, max_length=255, null=True, verbose_name='SPU')),
                ('suite_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='商家编码/条码')),
                ('u9_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='料品名称（U9）')),
            ],
        ),
    ]
