# Generated by Django 5.0.1 on 2024-04-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_spu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specgoods',
            name='spec_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='商家编码'),
        ),
        migrations.AddConstraint(
            model_name='platformgoods',
            constraint=models.UniqueConstraint(fields=('platform_goods_id', 'platform_spec_id'), name='unique_platformgoodsid_platformspecid'),
        ),
        migrations.AddConstraint(
            model_name='suitegoodsrec',
            constraint=models.UniqueConstraint(fields=('suite_no', 'spec_no'), name='unique_suiteno_specno'),
        ),
    ]
