# Generated by Django 5.0.1 on 2024-04-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_specgoods_spec_no_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='platformgoods',
            name='unique_platformgoodsid_platformspecid',
        ),
        migrations.AddConstraint(
            model_name='platformgoods',
            constraint=models.UniqueConstraint(fields=('shop_name', 'platform_goods_id', 'platform_spec_id'), name='unique_shopname_platformgoodsid_platformspecid'),
        ),
    ]
