# Generated by Django 5.0.1 on 2024-06-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_remove_platformgoods_unique_platformgoodsid_platformspecid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformgoods',
            options={'verbose_name': '旺店通平台货品', 'verbose_name_plural': '旺店通平台货品'},
        ),
        migrations.AlterModelOptions(
            name='specgoods',
            options={'verbose_name': '旺店通单品列表', 'verbose_name_plural': '旺店通单品列表'},
        ),
        migrations.AlterModelOptions(
            name='suitegoodsrec',
            options={'verbose_name': '旺店通组合装', 'verbose_name_plural': '旺店通组合装'},
        ),
    ]
