# Generated by Django 5.0.1 on 2024-06-19 14:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_platformgoods_options_alter_specgoods_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spu',
            options={'verbose_name': '商品SPU转换表', 'verbose_name_plural': '商品SPU转换表'},
        ),
        migrations.CreateModel(
            name='GoodsSalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='年度目标时间格式为YYYY，月度目标时间格式为YYYY-MM', regex='^\\d{4}(-\\d{2})?$')], verbose_name='目标时间')),
                ('num', models.IntegerField(verbose_name='目标销量')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='目标销售额')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.spu', verbose_name='SPU')),
            ],
            options={
                'verbose_name': '商品销售目标',
                'verbose_name_plural': '商品销售目标',
                'db_table': 'bi_goods_sales_target',
                'db_table_comment': '商品销售目标',
            },
        ),
        migrations.AddConstraint(
            model_name='goodssalestarget',
            constraint=models.UniqueConstraint(fields=('time', 'spu'), name='unique_time_spu'),
        ),
    ]
