# Generated by Django 5.0.1 on 2024-03-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=40, null=True, verbose_name='请求验证码ip')),
                ('areacode', models.CharField(blank=True, default='86', max_length=8)),
                ('mobile', models.CharField(help_text='手机号', max_length=32)),
                ('sms_token', models.CharField(help_text='验证码token', max_length=32)),
                ('sms_code', models.CharField(help_text='验证码', max_length=32)),
                ('createTime', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(blank=True, default=False, verbose_name='验证码是否已被使用')),
            ],
            options={
                'db_table': 'mobileAuthCode',
            },
        ),
    ]
