# Generated by Django 5.0.1 on 2024-03-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(blank=True, max_length=40, null=True, verbose_name='原始单号')),
                ('oid', models.CharField(blank=True, max_length=40, null=True, verbose_name='原始子订单号')),
                ('status', models.CharField(blank=True, max_length=40, null=True, verbose_name='状态')),
                ('process_status', models.CharField(blank=True, max_length=40, null=True, verbose_name='处理状态')),
                ('refund_status', models.CharField(blank=True, max_length=40, null=True, verbose_name='退款状态')),
                ('order_type', models.CharField(blank=True, max_length=40, null=True, verbose_name='子订单类型')),
                ('goods_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='平台货品id')),
                ('spec_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='平台规格id')),
                ('goods_no', models.CharField(blank=True, max_length=40, null=True, verbose_name='货品编号')),
                ('spec_no', models.CharField(blank=True, max_length=40, null=True, verbose_name='规格编码')),
                ('goods_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='货品名称')),
                ('spec_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='规格名称')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='单价')),
                ('adjust_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='调整')),
                ('discount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='优惠')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='总价')),
                ('share_discount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='分摊优惠')),
                ('share_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='分摊后应收')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='退款金额')),
                ('refund_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='退款单编号')),
                ('end_time', models.DateTimeField(blank=True, help_text='子单完成时间', null=True)),
                ('modified', models.DateTimeField(blank=True, help_text='修改时间', null=True)),
                ('created', models.DateTimeField(blank=True, help_text='创建时间', null=True)),
            ],
        ),
    ]
