# Generated by Django 5.0.1 on 2024-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_tid_alter_tradeorders_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeorders',
            name='oid',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='原始子订单号'),
        ),
        migrations.AddConstraint(
            model_name='tradeorders',
            constraint=models.UniqueConstraint(fields=('oid', 'spec_no'), name='unique_oid_spec_no'),
        ),
    ]
