# Generated by Django 5.0.1 on 2024-03-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_tradeorders_oid_tradeorders_unique_oid_spec_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradeorders',
            name='unique_oid_spec_no',
        ),
    ]
