# Generated by Django 5.0.1 on 2024-03-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_tradeorders_unique_oid_spec_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pay_account',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='买家支付账号'),
        ),
    ]
