# Generated by Django 5.0.1 on 2024-03-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_pay_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='bad_reason',
            field=models.TextField(blank=True, null=True, verbose_name='递交失败原因'),
        ),
        migrations.AddField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(blank=True, help_text='创建时间', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.TextField(blank=True, null=True, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='orders',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='结束时间', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='id_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='证件号码'),
        ),
        migrations.AddField(
            model_name='orders',
            name='invoice_content',
            field=models.TextField(blank=True, null=True, verbose_name='发票内容'),
        ),
        migrations.AddField(
            model_name='orders',
            name='invoice_type',
            field=models.CharField(blank=True, help_text='普通发票/电子发票/专用发票/全电普通发票/全电专用发票', max_length=40, null=True, verbose_name='发票类别'),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_auto_wms',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='是否自流转'),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_ware_trade',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='外部订单'),
        ),
        migrations.AddField(
            model_name='orders',
            name='logistics_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='物流编码'),
        ),
        migrations.AddField(
            model_name='orders',
            name='logistics_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='物流方式'),
        ),
        migrations.AddField(
            model_name='orders',
            name='modified',
            field=models.DateTimeField(blank=True, help_text='修改时间', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payer_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='对应发票抬头，付款方名称'),
        ),
        migrations.AddField(
            model_name='orders',
            name='trade_from',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='订单来源'),
        ),
    ]
