# Generated by Django 5.0.1 on 2024-03-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_bad_reason_orders_created_orders_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorders',
            name='image',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='tradeorders',
            name='sys_goods_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='系统货品名称'),
        ),
        migrations.AddField(
            model_name='tradeorders',
            name='sys_spec_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='系统规格名称'),
        ),
    ]
