# Generated by Django 5.0.1 on 2024-03-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_tradeorders_image_tradeorders_sys_goods_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeorders',
            name='oid',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='原始子订单号'),
        ),
    ]
