# Generated by Django 5.0.1 on 2024-04-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_tradeorders_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='对应发票抬头，付款方名称'),
        ),
        migrations.AlterField(
            model_name='tradeorders',
            name='goods_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='货品名称'),
        ),
        migrations.AlterField(
            model_name='tradeorders',
            name='spec_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='规格名称'),
        ),
        migrations.AlterField(
            model_name='tradeorders',
            name='sys_goods_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='系统货品名称'),
        ),
        migrations.AlterField(
            model_name='tradeorders',
            name='sys_spec_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='系统规格名称'),
        ),
    ]
