# Generated by Django 5.0.1 on 2024-04-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orders_created_alter_orders_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='佣金'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ext_cod_fee',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='买家COD费用'),
        ),
        migrations.AddField(
            model_name='orders',
            name='flag_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='标记名称'),
        ),
        migrations.AddField(
            model_name='orders',
            name='freeze_reason',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='冻结原因'),
        ),
        migrations.AddField(
            model_name='orders',
            name='goods_count',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='货品总数'),
        ),
        migrations.AddField(
            model_name='orders',
            name='goods_type_count',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='货品种类数'),
        ),
        migrations.AddField(
            model_name='orders',
            name='logistics_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='物流公司'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='orders',
            name='print_remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='打印备注'),
        ),
        migrations.AddField(
            model_name='orders',
            name='raw_goods_count',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='原始货品数量'),
        ),
        migrations.AddField(
            model_name='orders',
            name='raw_goods_type_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='原始货品种类数'),
        ),
        migrations.AddField(
            model_name='orders',
            name='receiver_dtb',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='大头笔'),
        ),
        migrations.AddField(
            model_name='orders',
            name='single_spec_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='货品商家编码'),
        ),
        migrations.AddField(
            model_name='orders',
            name='stockout_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='出库单号'),
        ),
        migrations.AddField(
            model_name='orders',
            name='trade_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='订单编号'),
        ),
        migrations.AddField(
            model_name='orders',
            name='warehouse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='仓库名称'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='biaoqi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标旗/客服标旗'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='buyer_message',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='买家备注/客户备注'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cash_on_delivery_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='货到付款金额/COD金额'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间/递交时间'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_term',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='货到付款/发货条件'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='goods_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='货款/货品总额'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='invoice_type',
            field=models.CharField(blank=True, help_text='否/普通发票/电子发票/专用发票/全电普通发票/全电专用发票', max_length=40, null=True, verbose_name='发票类别/需要发票'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='logistics_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='物流编码/物流单号'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay_account',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='买家支付账号/买家付款账号'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间/付款时间'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='发票抬头/付款方名称'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='post_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='邮费/邮资'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='process_status',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='系统处理状态/订单状态'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='receivable',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='应收/应收金额'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shop_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='店铺/店铺名称'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='to_deliver_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送货时间/派送时间'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='trade_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下单时间/交易时间'),
        ),
    ]
