# Generated by Django 5.0.1 on 2024-04-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_salesoutdetails_delete_tradeorders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoutdetails',
            name='ori_receivable',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='子单应收金额'),
        ),
    ]
