# Generated by Django 5.0.1 on 2024-04-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_salesoutdetails_ori_receivable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesoutdetails',
            constraint=models.UniqueConstraint(fields=('oid', 'stockout_no', 'goods_no'), name='unique_oid_stockoutno_goodsno'),
        ),
    ]
