# Generated by Django 5.0.1 on 2024-04-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_salesoutdetails_unique_oid_stockoutno_goodsno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoutdetails',
            name='oid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='原始子订单号'),
        ),
        migrations.AlterField(
            model_name='salesoutdetails',
            name='otid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='子单原始单号'),
        ),
        migrations.AlterField(
            model_name='salesoutdetails',
            name='tid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='原始单号'),
        ),
    ]
