# Generated by Django 5.0.1 on 2024-04-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_salesoutdetails_oid_alter_salesoutdetails_otid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoutdetails',
            name='remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
    ]
