# Generated by Django 5.0.1 on 2024-04-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_salesoutdetails_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoutdetails',
            name='source_suite_num',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True, verbose_name='来源组合装数量'),
        ),
    ]
