# Generated by Django 5.0.1 on 2024-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_salesoutdetails_source_suite_num'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesoutdetails',
            name='unique_oid_stockoutno_goodsno',
        ),
        migrations.AddConstraint(
            model_name='salesoutdetails',
            constraint=models.UniqueConstraint(fields=('oid', 'stockout_no', 'spec_no', 'goods_no'), name='unique_oid_stockoutno_specno_goodsno'),
        ),
    ]