# Generated by Django 5.0.1 on 2024-04-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_historysalesoutdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historysalesoutdetails',
            name='tid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='原始单号'),
        ),
    ]
