# Generated by Django 5.0.1 on 2024-04-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_historysalesoutdetails_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historysalesoutdetails',
            name='otid',
            field=models.TextField(blank=True, null=True, verbose_name='子单原始单号'),
        ),
        migrations.AlterField(
            model_name='historysalesoutdetails',
            name='tid',
            field=models.TextField(blank=True, null=True, verbose_name='原始单号'),
        ),
    ]
