# Generated by Django 5.0.1 on 2024-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_orderdetail_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderdetail',
            name='unique_oid_specno_goodsno_num',
        ),
        migrations.AddConstraint(
            model_name='orderdetail',
            constraint=models.UniqueConstraint(fields=('trade_no', 'oid', 'spec_no', 'goods_no', 'num'), name='unique_tradeno_oid_specno_goodsno_num'),
        ),
    ]
