# Generated by Django 5.0.1 on 2024-05-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_stockdetail_wmsshipdata_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockdetail',
            name='stockdetail_unique_specno_barcode_goodsno',
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='goods_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='货品编号'),
        ),
        migrations.AddConstraint(
            model_name='stockdetail',
            constraint=models.UniqueConstraint(fields=('spec_no', 'barcode', 'goods_no', 'qa_num'), name='stockdetail_unique_specno_barcode_goodsno_qanum'),
        ),
    ]
