# Generated by Django 5.0.1 on 2024-05-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_stockdetail_stockdetail_unique_specno_barcode_goodsno_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesoutdetails',
            name='unique_oid_stockoutno_specno_goodsno',
        ),
        migrations.AddConstraint(
            model_name='salesoutdetails',
            constraint=models.UniqueConstraint(fields=('oid', 'stockout_no', 'spec_no', 'goods_no', 'num'), name='unique_oid_stockoutno_specno_goodsno_num'),
        ),
    ]
