# Generated by Django 5.0.1 on 2024-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_remove_salesoutdetails_unique_oid_stockoutno_specno_goodsno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_no', models.CharField(max_length=100, verbose_name='退换单号')),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='店铺')),
                ('type', models.CharField(blank=True, max_length=40, null=True, verbose_name='类型')),
                ('status', models.CharField(blank=True, max_length=40, null=True, verbose_name='状态')),
                ('stock_status', models.CharField(blank=True, max_length=40, null=True, verbose_name='入库状态')),
                ('tid', models.CharField(blank=True, max_length=512, null=True, verbose_name='原始订单')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='系统订单')),
                ('original_exchange_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='原始退换单号')),
                ('buyer_nick', models.CharField(blank=True, max_length=100, null=True, verbose_name='网名')),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('receiver_telno', models.CharField(blank=True, max_length=40, null=True, verbose_name='电话')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='退货金额')),
                ('platform_refund', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='平台退款金额')),
                ('offline_refund', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='线下退款金额')),
                ('collection_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='收款金额')),
                ('refund', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='实际退款')),
                ('logistics_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='退回物流公司')),
                ('logistics_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='退回物流单号')),
                ('warehouse', models.CharField(blank=True, max_length=100, null=True, verbose_name='退货仓库')),
                ('data_source', models.CharField(blank=True, max_length=40, null=True, verbose_name='建单方式')),
                ('exchange_remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='退换说明')),
                ('refuse_reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='驳回原因')),
                ('mark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='标记')),
                ('creater', models.CharField(blank=True, max_length=40, null=True, verbose_name='建单者')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(blank=True, null=True, verbose_name='建单时间')),
                ('updated_time', models.DateTimeField(blank=True, null=True, verbose_name='最后修改时间')),
                ('exchange_info', models.CharField(blank=True, max_length=40, null=True, verbose_name='退换信息')),
                ('distributor_exchange_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='分销商退换单号')),
                ('refund_num', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='退款数量')),
                ('distributor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='分销商名称')),
                ('distributor_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='分销商编号')),
                ('refund_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='退款原因')),
                ('wms_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='wms业务单号')),
                ('error_msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='错误信息')),
                ('distributor_tid', models.CharField(blank=True, max_length=100, null=True, verbose_name='分销原始单号')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exchangemanagement',
            constraint=models.UniqueConstraint(fields=('exchange_no', 'tid', 'trade_no', 'original_exchange_no'), name='exchangemag_unique_exchangeno_tid_tradeno_oriexchangeno'),
        ),
    ]
