# Generated by Django 5.0.1 on 2024-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_exchangemanagement_trade_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=40, null=True, verbose_name='渠道')),
                ('platform', models.CharField(blank=True, max_length=40, null=True, verbose_name='平台')),
                ('principal', models.CharField(blank=True, max_length=40, null=True, verbose_name='负责人')),
                ('shop_name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('wdt_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='旺店通名称')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='年度目标')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shoptarget',
            constraint=models.UniqueConstraint(fields=('shop_name', 'year'), name='shoptarget_unique_name_year'),
        ),
    ]
