# Generated by Django 5.0.1 on 2024-05-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_remove_shoptarget_shoptarget_unique_name_year_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesoutdetails',
            index=models.Index(fields=['otid'], name='orders_sale_otid_2e108d_idx'),
        ),
    ]
