# Generated by Django 5.0.1 on 2024-06-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_salesoutdetails_orders_sale_otid_2e108d_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historysalesoutdetails',
            name='historysalesout_unique_oid_stockoutno_specno_goodsno',
        ),
        migrations.AddIndex(
            model_name='historysalesoutdetails',
            index=models.Index(fields=['otid'], name='orders_hist_otid_b9f4f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='historysalesoutdetails',
            constraint=models.UniqueConstraint(fields=('oid', 'stockout_no', 'spec_no', 'goods_no', 'num'), name='unique_history_salesout_details'),
        ),
    ]
