# Generated by Django 5.0.1 on 2024-06-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_remove_historysalesoutdetails_historysalesout_unique_oid_stockoutno_specno_goodsno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptarget',
            name='need_summary',
            field=models.BooleanField(default=True, verbose_name='是否需要汇总（财务系统用）'),
        ),
    ]
