# Generated by Django 5.0.1 on 2024-06-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_shoptarget_need_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangemanagement',
            options={'verbose_name': '旺店通退换管理', 'verbose_name_plural': '旺店通退换管理'},
        ),
        migrations.AlterModelOptions(
            name='historysalesoutdetails',
            options={'verbose_name': '旺店通历史销售出库明细', 'verbose_name_plural': '旺店通历史销售出库明细'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': '旺店通订单明细', 'verbose_name_plural': '旺店通订单明细'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': '旺店通原始订单+历史订单', 'verbose_name_plural': '旺店通原始订单+历史订单'},
        ),
        migrations.AlterModelOptions(
            name='salesoutdetails',
            options={'verbose_name': '旺店通销售出库明细', 'verbose_name_plural': '旺店通销售出库明细'},
        ),
        migrations.AlterModelOptions(
            name='shoptarget',
            options={'verbose_name': '各店铺年度目标', 'verbose_name_plural': '各店铺年度目标'},
        ),
        migrations.AlterModelOptions(
            name='stockdetail',
            options={'verbose_name': '旺店通库存管理', 'verbose_name_plural': '旺店通库存管理'},
        ),
        migrations.AlterModelOptions(
            name='wmsshipdata',
            options={'verbose_name': '旺店通WMS发货数据', 'verbose_name_plural': '旺店通WMS发货数据'},
        ),
    ]
