# Generated by Django 5.0.1 on 2024-06-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_exchangemanagement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdetail',
            options={'verbose_name': '旺店通库存明细', 'verbose_name_plural': '旺店通库存明细'},
        ),
        migrations.RemoveConstraint(
            model_name='stockdetail',
            name='stockdetail_unique_specno_barcode_goodsno_qanum',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='lowest_price',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='market_price',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='member_price',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='onsale_time',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='outside_stock_num',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='stock_diff',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='sync_time',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='wholesale_price',
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='material_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='U9料号'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='spec_created',
            field=models.DateTimeField(blank=True, help_text='单品创建时间', null=True),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='税率'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='is_defective',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='残次品'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='sale_return_ontheway_num',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='退货在途量'),
        ),
    ]
