# Generated by Django 5.0.1 on 2024-06-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_shopsalestarget_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoptarget',
            options={'verbose_name': '店铺', 'verbose_name_plural': '店铺'},
        ),
    ]
