# Generated by Django 5.0.1 on 2024-07-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_alter_shopsalestarget_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemanagement',
            name='original_exchange_no',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='原始退换单号'),
        ),
    ]
