# Generated by Django 5.0.1 on 2024-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_alter_exchangemanagement_original_exchange_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='spec_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='单品创建时间'),
        ),
    ]
