# Generated by Django 5.0.1 on 2024-07-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_alter_stockdetail_spec_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historysalesoutdetails',
            name='deal_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='分摊后单价'),
        ),
        migrations.AlterField(
            model_name='historysalesoutdetails',
            name='deal_total_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='分摊后总价'),
        ),
        migrations.AlterField(
            model_name='salesoutdetails',
            name='deal_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='分摊后单价'),
        ),
        migrations.AlterField(
            model_name='salesoutdetails',
            name='deal_total_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='分摊后总价'),
        ),
    ]
