# Generated by Django 5.0.1 on 2024-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_alter_historysalesoutdetails_deal_price_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesoutdetails',
            index=models.Index(fields=['trade_no'], name='orders_sale_trade_n_5ebba6_idx'),
        ),
    ]
