# Generated by Django 5.0.1 on 2024-08-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_wmsshipdata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptarget',
            name='org',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='组织'),
        ),
        migrations.AddField(
            model_name='shoptarget',
            name='salesman',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='业务员'),
        ),
        migrations.AddField(
            model_name='shoptarget',
            name='team',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='团队'),
        ),
    ]
