# Generated by Django 5.0.1 on 2024-05-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tmallrefund',
            constraint=models.UniqueConstraint(fields=('trade_no', 'refund_no', 'alipay_transaction_no', 'goods_no'), name='unique_tradeno_refundno_alipaytransactionno_goodsno'),
        ),
    ]
