# Generated by Django 5.0.1 on 2024-05-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_tmallrefund_goods_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmallrefund',
            name='goods_return',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='是否需要退货'),
        ),
        migrations.AlterField(
            model_name='tmallrefund',
            name='refund_source',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='手工退款_系统退款'),
        ),
    ]
