# Generated by Django 5.0.1 on 2024-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_pddrefund_unique_tradeno_goodsid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsSalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('spec_no', models.CharField(max_length=100, verbose_name='商家编码')),
                ('major_supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='主供应商')),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='店铺')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='品牌')),
                ('goods_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类')),
                ('goods_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='货品编号')),
                ('goods_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='货品名称')),
                ('spec_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='规格名称')),
                ('goods_category', models.CharField(blank=True, max_length=40, null=True, verbose_name='货品类别')),
                ('average_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='均价')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='零售价')),
                ('ship_num', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='发货总量')),
                ('return_num', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='退货入库量（原退货总量）')),
                ('return_count_num', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='退货入库结算量')),
                ('sales_num', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='实际销售量')),
                ('ship_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='发货总金额')),
                ('sales_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='销售总金额')),
                ('sales_amount_unknown_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='未知成本销售总额')),
                ('return_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='退货总金额（结算）')),
                ('actual_sales_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='实际销售额')),
                ('gift_sales_num', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='赠品销量')),
                ('post_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='邮费')),
                ('post_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='邮资成本')),
                ('ship_refund_num', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='系统发货但平台退款量')),
                ('ship_refund_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='系统发货但平台退款金额')),
                ('abnormal_warehouse_sales_num', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='异常仓销量')),
                ('refund_stockin', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='退货总金额（入库）')),
            ],
        ),
        migrations.AddConstraint(
            model_name='goodssalessummary',
            constraint=models.UniqueConstraint(fields=('start_date', 'spec_no', 'shop_name'), name='unique_startdate_specno_shopname'),
        ),
    ]
