# Generated by Django 5.0.1 on 2024-05-25 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_rename_u9_no_financesalesandinvoice_material_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesalesandinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financesalesandinvoice',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期（统计）'),
        ),
        migrations.AddField(
            model_name='financesalesandinvoice',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期（统计）'),
        ),
        migrations.AlterField(
            model_name='financesalesandinvoice',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='开票/退款日期'),
        ),
    ]
