# Generated by Django 5.0.1 on 2024-05-29 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_financesalesandinvoice_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_tradeno_goodsmodel_goodstotalamount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='入库时间'),
            preserve_default=False,
        ),
    ]
