# Generated by Django 5.0.1 on 2024-05-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_invoice_unique_tradeno_goodsmodel_goodstotalamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='trade_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='订单id'),
        ),
    ]
