# Generated by Django 5.0.1 on 2024-05-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_invoice_trade_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tmallrefund',
            name='unique_tradeno_refundno_alipaytransactionno_goodsno',
        ),
        migrations.RemoveField(
            model_name='tmallrefund',
            name='logistics_name',
        ),
        migrations.RemoveField(
            model_name='tmallrefund',
            name='logistics_no',
        ),
        migrations.RemoveField(
            model_name='tmallrefund',
            name='return_logistics_info',
        ),
        migrations.RemoveField(
            model_name='tmallrefund',
            name='seller_mobile',
        ),
        migrations.RemoveField(
            model_name='tmallrefund',
            name='seller_return_address',
        ),
        migrations.RemoveField(
            model_name='tmallrefund',
            name='seller_telno',
        ),
        migrations.RemoveField(
            model_name='tmallrefund',
            name='seller_zip',
        ),
        migrations.AddField(
            model_name='tmallrefund',
            name='refund_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='部分退款_全部退款'),
        ),
        migrations.AlterField(
            model_name='tmallrefund',
            name='refund_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='退款编号'),
        ),
    ]
