# Generated by Django 5.0.1 on 2024-06-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_tmallrefund_unique_tradeno_refundno_alipaytransactionno_goodsno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmallrefund',
            old_name='refund_apply_time',
            new_name='apply_time',
        ),
    ]
