# Generated by Django 5.0.1 on 2024-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_douyinrefund_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('invoice_time', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='订货客户')),
                ('goods_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='货号')),
                ('goods_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='品名')),
                ('goods_num', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='数量')),
                ('goods_total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='价税合计')),
            ],
            options={
                'verbose_name': '发票财务手工调整',
                'verbose_name_plural': '发票财务手工调整',
                'db_table': 'finance_invoice_manual',
                'db_table_comment': '财务手工调整的发票',
            },
        ),
    ]
