# Generated by Django 5.0.1 on 2024-06-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_invoicemanual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '发票阿里', 'verbose_name_plural': '发票阿里'},
        ),
        migrations.AlterModelTableComment(
            name='invoice',
            table_comment='阿里发票',
        ),
    ]
