# Generated by Django 5.0.1 on 2024-06-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_invoice_options_alter_invoice_table_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='douyinrefund',
            options={'verbose_name': '仅退款抖音', 'verbose_name_plural': '仅退款抖音'},
        ),
        migrations.AlterModelOptions(
            name='invoicemanual',
            options={'verbose_name': '发票手工', 'verbose_name_plural': '发票手工'},
        ),
        migrations.AlterModelOptions(
            name='jdrefund',
            options={'verbose_name': '仅退款京东', 'verbose_name_plural': '仅退款京东'},
        ),
        migrations.AlterModelOptions(
            name='pddrefund',
            options={'verbose_name': '仅退款拼多多', 'verbose_name_plural': '仅退款拼多多'},
        ),
        migrations.AlterModelOptions(
            name='tmallrefund',
            options={'verbose_name': '仅退款天猫', 'verbose_name_plural': '仅退款天猫'},
        ),
    ]
