# Generated by Django 5.0.1 on 2024-07-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_remove_jdrefund_unique_refundno_tradeno_serviceno_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pddrefund',
            name='unique_tradeno_goodsid_applicant',
        ),
    ]
